#!/usr/bin/env php

<?php

require_once __DIR__.'/vendor/autoload.php';

require_once __DIR__.'/storage/src/forge/console/Forge.php';

use Bimp\Forge\Console\Forge;

$console = new Forge();
exit($console->run($argv));
